---
# InfluxDB repository (influxdata) is configured by dj-wasabi.telegraf

- name: Install InfluxDB
  ansible.builtin.apt:
    name: influxdb
    state: "{{ 'latest' if influxdb_upgrade else 'present' }}"
    update_cache: true
