---
- name: Include install tasks
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"

# If influxdb_user is defined, we assume non-standard dir paths
- name: Create InfluxDB directories
  when: influxdb_user is defined
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ influxdb_user }}"
    group: "{{ influxdb_user }}"
    mode: "0750"
  loop:
    - "{{ influxdb_conf_dir }}"
    - "{{ influxdb_var_dir }}"

- name: Copy InfluxDB configs
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ influxdb_conf_dir }}/{{ item }}"
    mode: "0644"
    backup: "{{ influxdb_backup_configs }}"
  loop:
    - influxdb.conf
  notify:
    - Restart influxdb

# Force a restart in case connection params have changed
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure InfluxDB is started and running
  ansible.builtin.systemd_service:
    name: "{{ influxdb_service_name }}"
    state: started
    enabled: true

# Create at least one admin user
- name: Create InfluxDB admin user
  when: influxdb_admin_user is defined
  ansible.builtin.uri:
    url: "{{ influxdb_http_protocol }}{{ influxdb_http_bind_address }}/query"
    method: POST
    body_format: form-urlencoded
    body:
      q: "CREATE USER {{ influxdb_admin_user }} WITH PASSWORD '{{ influxdb_admin_password }}' WITH ALL PRIVILEGES"
    url_username: "{{ influxdb_admin_user }}"
    url_password: "{{ influxdb_admin_password }}"
    status_code: 200
  no_log: true

# Create regular users
- name: Create InfluxDB users
  when: influxdb_users is defined
  ansible.builtin.uri:
    url: "{{ influxdb_http_protocol }}{{ influxdb_http_bind_address }}/query"
    method: POST
    body_format: form-urlencoded
    body:
      q: "CREATE USER {{ item.user_name }} WITH PASSWORD '{{ item.user_password }}'{{ ' WITH ALL PRIVILEGES' if item.admin | default(false) else '' }}"
    url_username: "{{ influxdb_admin_user }}"
    url_password: "{{ influxdb_admin_password }}"
    status_code: 200
  loop: "{{ influxdb_users | default([]) }}"
  loop_control:
    label: "{{ item.user_name }}"
  no_log: true
