---
# InfluxDB repository (influxdata) is configured by dj-wasabi.telegraf

# the new influxd-system-start.sh health checks are fairly broken
- name: Install InfluxDB systemd service unit
  copy:
    src: redhat/influxdb.service
    dest: /etc/systemd/system/influxdb.service
    owner: root
    group: root
    mode: "0644"
  register: __influxdb_service_unit_result

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: __influxdb_service_unit_result is changed

- name: Install InfluxDB
  ansible.builtin.yum:
    name: influxdb
    state: "{{ 'latest' if influxdb_upgrade else 'present' }}"
    update_cache: true
