---
# Create at least one admin user
- name: Create InfluxDB admin user
  when: influxdb_admin_user is defined
  ansible.builtin.uri:
    url: "{{ influxdb_http_service_uri }}/query"
    method: POST
    body_format: form-urlencoded
    body:
      q: "CREATE USER {{ influxdb_admin_user }} WITH PASSWORD '{{ influxdb_admin_password }}' WITH ALL PRIVILEGES"
    url_username: "{{ influxdb_admin_user }}"
    url_password: "{{ influxdb_admin_password }}"
    status_code: 200
  register: _influxdb_admin_create
  no_log: true

# Ensure user password is updated if user exists
- name: Update InfluxDB admin user password
  when:
    - influxdb_admin_user is defined
    - _influxdb_admin_create.json.results[0].error is defined
  ansible.builtin.uri:
    url: "{{ influxdb_http_service_uri }}/query"
    method: POST
    body_format: form-urlencoded
    body:
      q: "ALTER USER {{ influxdb_admin_user }} WITH PASSWORD '{{ influxdb_admin_password }}'"
    url_username: "{{ influxdb_admin_user }}"
    url_password: "{{ influxdb_admin_password }}"
    status_code: 200
  no_log: true

# Create regular users
- name: Create InfluxDB users
  when: influxdb_users is defined
  ansible.builtin.uri:
    url: "{{ influxdb_http_service_uri }}/query"
    method: POST
    body_format: form-urlencoded
    body:
      q: "CREATE USER {{ item.user_name }} WITH PASSWORD '{{ item.user_password }}'{{ ' WITH ALL PRIVILEGES' if item.admin | default(false) else '' }}"
    url_username: "{{ influxdb_admin_user }}"
    url_password: "{{ influxdb_admin_password }}"
    status_code: 200
  loop: "{{ influxdb_users | default([]) }}"
  loop_control:
    label: "{{ item.user_name }}"
  register: _influxdb_users_create
  no_log: true

- name: Update InfluxDB user passwords
  when:
    - influxdb_users is defined
    - item.json.results[0].error is defined
  ansible.builtin.uri:
    url: "{{ influxdb_http_service_uri }}/query"
    method: POST
    body_format: form-urlencoded
    body:
      q: "ALTER USER {{ item.item.user_name }} WITH PASSWORD '{{ item.item.user_password }}'"
    url_username: "{{ influxdb_admin_user }}"
    url_password: "{{ influxdb_admin_password }}"
    status_code: 200
  loop: "{{ _influxdb_users_create.results }}"
  loop_control:
    label: "{{ item.item.user_name }}"
  no_log: true
